name: openframeworks Forum RSS generator

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: scrape
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run scraper
        run: pnpm run scrape

      - name: Debug output (status + list)
        run: |
          echo "Git status:"
          git status
          echo "Files in docs/:"
          ls -la docs/ || true
          echo "feed.xml head:"
          head -n 20 docs/feed.xml || true
          echo "Diff (docs/):"
          git --no-pager diff --stat docs/ || true

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # stage generated files
          git add docs/

          # commit only if there are staged changes
          if ! git diff --staged --quiet; then
            git commit -m "Update scraped data [skip ci]"
            # push explicitly to main to avoid detached HEAD issues
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
